# -*- coding: utf-8 -*-
"""DemoGitHub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/binary-study/DemoBinary/blob/main/DemoGitHub.ipynb

# CONTENT:
# git init
# git clone
# git remote
# git status
# git add
# git commit
# git config
# git push
"""

! git

! git init

! git clone https://github.com/binary-study/DemoBinary.git

! pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd DemoBinary/

! git remote -v

! git status

! touch firstpython.py

! python myfile.py

! git status

! git add -A

! git status

! git commit -a -m "first commit"

! git config --global user.email "bianrystudy21@gmail.com"
! git config --global user.name "binary-study"

! git config --list

! git commit -a -m "first commit"

! git status

username = input("Enter username: ")

from getpass import getpass
password = getpass("Enter password: ")

!git remote add origin https://$username:$password@github.com/$username/DemoBinary.git

!git remote rm origin

!git remote add origin https://$username:$password@github.com/$username/DemoBinary.git

! git push origin main

! git log

